### ISSUE TITLE
训练集

### ISSUE THREAD

**Issue by clelouch** [blanclist/CDNet#5]
您好，我注意到不同方法用的训练集有些区别。我想确认一下，您在table1的结果是否是1485 NJU2K + 700 NLPR作为训练集的结果。然后在table2中的是否是1485 NJU2K + 700 NLPR + 800 DUT结果？

**Comment by blanclist** [comment]
您理解的没错，我们这样做的目的是为了保证实验公平。在D3Net之前，大家都是将NJU2K+NLPR中的一部分作为训练集，剩下的图片分别作为NJU2K和NLPR的测试集。这里训练集的容量有的是2185（1485+700），有的方法可能有一点变化，但整体来说没什么太大影响。不过需要注意的是，我们在拿到CPFP的测试结果后发现，其在训练集上的划分和大部分方法都不相同，这就导致了CPFP所使用的NJU2K、NLPR测试集和我们常用的并不相同（常用的测试集中的图片可能被用作CPFP的训练，而常用的训练集中的图片可能被用作CPFP的测试）。所以在评测CPFP的效果时，我们仅仅是对测试集中重叠的部分进行了评测。不过CPFP相较于现有的方法来说效果本来就不是很好，所以您或许也不需要比较这个方法。在DMRA方法中，作者开始额外使用了它们提出的DUT数据集，将其分为800张训练图片和400张测试图片。从这个方法开始，可以看到很多人的训练集构成不再是2185张图片（1485 NJU2K + 700 NLPR），而是2985张图片（1485 NJU2K + 700 NLPR + 800 DUT）。我个人认为之所以要使用这个额外的训练集，是为了提升RGB-D模型在LFSD数据集上的效果，因为DUT和LFSD的深度图分布是一致的。从结果上来看，也可以发现在此之后的模型在LFSD数据集上的效果相较于之前都有很明显的提升。虽然我个人认为这种粗暴的方式不是很合理（NJU2K、NLPR和DUT的深度图分布明显不一致），但如果我不使用这个额外的DUT数据集来训练，那么我的模型在LFSD测试集上就很难超过其余SOTA模型。所以出于公平性的考虑，我们最终按照训练集的不同（是否使用DUT）将当时的方法分为了两类，并且分别训练了两个CDNet作为比较。

**Comment by clelouch** [comment]
好的，非常感谢您的回答: )
